name: Casual GAN Papers
description: Easy to read summaries of popular AI papers
meta_description: "Popular deep learning & machine learning papers explained in 5 minutes twice a week"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "https://casualganpapers.com"
google_analytics: "UA-163377075-3"
plugins: [jekyll-paginate, jekyll-sitemap]

# Details for the RSS feed generator
url: "https://casualganpapers.com"
author: "Kirill Demochkin"

# Disqus config
disqus-shortname: ""
