name: Your New Jekyll Site
description: Easy to read summaries of popular ML/DL papers
meta_description: "Popular deep learning & machine learning papers explained casually twice a week"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "https://casualganpapers.com"
google_analytics: "UA-163377075-3"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Kirill Demochkin"

# Disqus config
disqus-shortname: ""
